const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "2023 - present",
      title: "Ingenieria en Informática",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 2,
      category: "education",
      icon: "HML responsive design",
      year: "2022",
      title: "FreeCodecamp Certification",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2019 - 2022",
      title: "Bachillerato Técnico en Informatica",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "2019 - present",
      title: "Web Designer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "2013 - 2017",
      title: "Front-End Developer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "2009 - 2013",
      title: "Back-End Developer",
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
  ];
export default Data  